In [1]:
import pandas as pd


df=pd.read_csv('review.csv')
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,uYHaNptLzDLoV_JZ_MuzUA,0,2016-07-12,0.0,VfBHSwC5Vz_pbFluy07i9Q,5.0,My girlfriend and I stayed here for 3 nights a...,0.0,cjpdDjZyprfyDG3RlkVG3w
1,uYHaNptLzDLoV_JZ_MuzUA,0,2016-10-02,0.0,3zRpneRKDsOPq92tq7ybAA,3.0,If you need an inexpensive place to stay for a...,0.0,bjTcT8Ty4cJZhEOEo01FGA
2,uYHaNptLzDLoV_JZ_MuzUA,0,2015-09-17,0.0,ne5WhI1jUFOcRn-b-gAzHA,3.0,Mittlerweile gibt es in Edinburgh zwei Ableger...,0.0,AXgRULmWcME7J6Ix3I--ww
3,uYHaNptLzDLoV_JZ_MuzUA,0,2016-08-21,0.0,llmdwOgDReucVoWEry61Lw,4.0,Location is everything and this hotel has it! ...,0.0,oU2SSOmsp_A8JYI7Z2JJ5w
4,uYHaNptLzDLoV_JZ_MuzUA,0,2013-11-20,0.0,DuffS87NaSMDmIfluvT83g,5.0,gute lage im stadtzentrum. shoppingmeile und s...,0.0,0xtbPEna2Kei11vsU-U2Mw